---
title: "COVID INCIDENCE"
output:
  html_document:
    df_print: paged
---

```{r}
pacman::p_load(openxlsx,tibbletime,tidyverse,lubridate,tidyr,dplyr,tibble)
# knitr::opts_knit$set(root.dir = '/Users/ChristianKruse\ 1/Documents/OneDrivePrivat/OneDrive/COVID_INCIDENCE_2',
#                      scipen=999)
knitr::opts_knit$set(root.dir = 'C:/Users/Christian/OneDrive/COVID_INCIDENCE_2',
                     scipen=999)
data_files <- file.info(list.files(path = "Data",pattern = ".zip",full.names = TRUE)) %>% 
  slice_max(mtime)
```

```{r unzip}
current_file <- row.names(data_files)
unzip(current_file,exdir = "Data",overwrite = TRUE)
```

```{r}
rolling_sum <- rollify(.f = sum, window = 14)
```


```{r}

setClass("num.with.commas")
setAs("character", "num.with.commas", 
        function(from) as.numeric(gsub(",", "", from) ) )

df <-
  read.csv("Data/Test_pos_over_time.csv",
           sep = ";",
           colClasses=c('character',
                        'character',
                        'character',
                        'character',
                        'character',
                        'character',
                        'character')) %>%
  dplyr::slice(c(1:(nrow(.)-2))) %>% 
  as_tibble()

df$NewPositive <- df  %>% 
  pull(NewPositive) %>% 
  trimws %>% 
  gsub("\\.","",.)

df <- df %>% 
  dplyr::mutate(NewPositive=readr::parse_number(NewPositive)) %>% 
  dplyr::mutate(NewPositive==gsub(pattern = "\\.",replacement = "_",x = NewPositive)) %>% 
  dplyr::mutate(NewPositive==gsub(pattern = ",",replacement = "",x = NewPositive)) %>% 
  dplyr::mutate(Date=ymd(Date),
                NewPositive=as.integer(NewPositive)) %>% 
  dplyr::mutate(ROLLING_SUM=lag(rolling_sum(NewPositive))) %>%
  dplyr::mutate(INCIDENCE=ROLLING_SUM/(5824857/100000)) %>%
  dplyr::mutate(Date=ymd(Date)) %>%
  dplyr::select(Date,NewPositive,ROLLING_SUM,INCIDENCE)

```

# 14 Day Incidence

```{r incidence}

## DESCENT #1
df.fit.descent <- 
  df %>%
  filter(Date>=ymd("2020-09-29")) %>%
  filter(Date<=ymd("2020-10-14"))

fit.incidence.descent <- 
  lm(log10(INCIDENCE)~Date,data=df.fit.descent)

predicted.incidence.descent <- 
  10^predict(fit.incidence.descent,
             data.frame(Date=seq.Date(ymd("2020-09-29"),ymd("2021-03-01"),by = "1 day"))) %>%
  tbl_df() %>%
  dplyr::mutate(Date=seq.Date(ymd("2020-09-29"),ymd("2021-03-01"),by = "1 day"))

break_even_date.descent <- 
  predicted.incidence.descent %>% filter(value>60) %>% slice(nrow(.)) %>% .[["Date"]]

## INCREASE #1
df.fit.increase <- 
  df %>%
  filter(Date>=ymd("2020-10-14")) %>%
  filter(Date<=ymd("2020-11-03"))

fit.incidence.increase <- 
  lm(log10(INCIDENCE)~Date,data=df.fit.increase)

summary(fit.incidence.increase)

predicted.incidence.increase <- 
  10^predict(fit.incidence.increase,
             data.frame(Date=seq.Date(ymd("2020-10-14"),ymd("2020-11-03"),by = "1 day"))) %>%
  tbl_df() %>%
  dplyr::mutate(Date=seq.Date(ymd("2020-10-14"),ymd("2020-11-03"),by = "1 day"))

break_even_date.increase <- 
  predicted.incidence.increase %>% filter(value>60) %>% slice(nrow(.)) %>% .[["Date"]]

## INCREASE #2
df.fit.increase_2 <- 
  df %>%
  filter(Date>=ymd("2020-12-01"))

fit.incidence.increase <- 
  lm(log10(INCIDENCE)~Date,data=df.fit.increase_2)

summary(fit.incidence.increase)

predicted.incidence.increase_2 <- 
  10^predict(fit.incidence.increase,
             data.frame(Date=seq.Date(ymd("2020-12-01"),ymd("2021-03-01"),by = "1 day")),
        interval = "prediction") %>%
  tbl_df() %>%
  dplyr::mutate(Date=seq.Date(ymd("2020-12-01"),ymd("2021-03-01"),by = "1 day")) %>% 
  dplyr::rename(value=fit)

break_even_date.increase_2 <- 
  predicted.incidence.increase_2 %>% filter(value>60) %>% slice(nrow(.)) %>% .[["Date"]]

# Most recent 14 days

df %>% tail(14) %>% knitr::kable()

# PLOT
df %>%
  ggplot(.,aes(x=Date,y=INCIDENCE)) +
  geom_point() +
  scale_x_date(date_breaks = "1 week",limits=c(dmy("26-02-2020"),dmy("01-03-2021")),date_labels = "%d-%m") +
  scale_y_continuous(limits=c(0,750),breaks=seq(0,750,by=25)) +
  geom_hline(yintercept = 60,color="green") +
  geom_abline(slope = -1,intercept = 200) +
  geom_line(data=predicted.incidence.descent,aes(x=Date,y=value),color="blue") +
  geom_line(data=predicted.incidence.increase,aes(x=Date,y=value),color="red") +
  geom_line(data=predicted.incidence.increase_2,aes(x=Date,y=value),color="green") +
  geom_line(data=predicted.incidence.increase_2,aes(x=Date,y=lwr),color="black") +
  geom_line(data=predicted.incidence.increase_2,aes(x=Date,y=upr),color="black") +
  geom_vline(xintercept = unique(floor_date(seq.Date(dmy("01-08-2020"),dmy("01-08-2030"),by="1 day"),"month")),color="blue") +
  # geom_vline(xintercept = unique(floor_date(seq.Date(dmy("01-08-2020"),dmy("01-08-2030"),by="1 day"),"week")),color="grey50") +
  geom_hline(yintercept = c(100,125,150)) + 
  # geom_vline(xintercept = break_even_date,color="red") +
  theme(axis.text.x = element_text(angle = 90)) +
  labs(x="Date",y="14-day Incidence Per 100,000") 


```

# Number of Tests

```{r}

  read.csv("Data/Test_pos_over_time.csv",sep = ";") %>% 
  slice(c(1:(nrow(.)-2))) %>% 
  as_tibble() %>% 
  dplyr::mutate(Date=ymd(Date),
                Tested=as.integer(gsub("\\.","",Tested))) %>% 
  ggplot(.,aes(x=Date,y=Tested)) +
  geom_line() +
  theme(axis.text.x = element_text(angle = 90)) +
  labs(x="Date",y="Number of Daily Tests") +
  scale_x_date(date_breaks = "1 week",limits=c(dmy("26-02-2020"),dmy("01-01-2021")),date_labels = "%d-%m") +
    scale_y_continuous(limits=c(0,150000),breaks=seq(0,150000,by=5000))



```

# Number of Tests versus positive percentage

```{r}

  read.csv("Data/Test_pos_over_time.csv",sep = ";") %>% 
  slice(c(1:(nrow(.)-2))) %>% 
  as_tibble() %>% 
  dplyr::mutate(Date=ymd(Date),
                Tested=as.integer(gsub("\\.","",Tested)),
                PosPct=as.numeric(gsub("\\,",".",PosPct))) %>% 
  ggplot(.,aes(x=Tested,y=PosPct)) +
  geom_point() +
  theme(axis.text.x = element_text(angle = 90)) +
  labs(x="Number of tests",y="Positive Percentage") +
  # scale_x_date(date_breaks = "1 week",limits=c(dmy("26-02-2020"),dmy("01-01-2021")),date_labels = "%d-%m") +
    scale_y_continuous(limits=c(0,NA))



```
# % Positive

```{r}

  read.csv("Data/Test_pos_over_time.csv",sep = ";") %>% 
  slice(c(1:(nrow(.)-2))) %>% 
  as_tibble() %>% 
  dplyr::mutate(Date=ymd(Date),
                PosPct=as.numeric(gsub("\\,",".",PosPct))) %>% 
  ggplot(.,aes(x=Date,y=PosPct)) +
  geom_line() +
  theme(axis.text.x = element_text(angle = 90)) +
  labs(x="Date",y="% Positive") +
  scale_x_date(date_breaks = "1 week",limits=c(dmy("26-02-2020"),dmy("01-01-2021")),date_labels = "%d-%m")



```

# Admissions

```{r}

  read.csv("Data/Newly_admitted_over_time.csv",sep = ";") %>% 
  select(c(1:6,8)) %>% 
  setNames(.,c("Dato","Hovedstaden","Sjælland","Syddanmark","Midtjylland","Nordjylland","Total")) %>% 
  gather(Metric,Value,Hovedstaden:Total) %>% 
  dplyr::mutate(Dato=ymd(Dato)) %>% 
  ggplot(.,aes(x=Dato,y=Value,color=Metric,group=Metric)) +
  # geom_point() +
  geom_line() +
  scale_x_date(date_breaks = "4 week",date_labels = "%d-%m")

```

# Switzerland

```{r}

data_files <- file.info(list.files(path = "Data",pattern = "labtests_positivity",full.names = TRUE)) %>% 
  slice_max(mtime)

## Switzerland data
df.switzerland <-
  openxlsx::read.xlsx(row.names(data_files)) %>% 
  as_tibble() %>% 
  dplyr::mutate(Datum=as.Date(Datum,origin="1899-12-30")) %>% 
  dplyr::select(-Replikation_dt)


```

```{r}

### INCIDENCE

# Positive
df.switzerland.positive <- df.switzerland %>% 
  filter(Outcome_tests=="Positive") %>%
  rename(Date=Datum,
         NewPositive=Number_of_tests) %>% 
  dplyr::mutate(ROLLING_SUM=lag(rolling_sum(NewPositive))) %>%
  dplyr::mutate(INCIDENCE=ROLLING_SUM/(8570146/100000)) %>%
  dplyr::mutate(Date=ymd(Date)) %>%
  dplyr::select(Date,NewPositive,ROLLING_SUM,INCIDENCE)

df.switzerland.positive %>% as_tibble() %>% tail(14) %>% knitr::kable() 

# INCREASE
df.fit.increase.swiss <- 
  df.switzerland.positive %>%
  filter(Date>=ymd("2020-10-01")) %>% 
  filter(Date<=ymd("2020-11-09"))

fit.incidence.increase.swiss <- 
  lm(log10(INCIDENCE)~Date,data=df.fit.increase.swiss)

summary(fit.incidence.increase.swiss)

predicted.incidence.increase.swiss <- 
  10^predict(fit.incidence.increase.swiss,
             data.frame(Date=seq.Date(ymd("2020-10-14"),ymd("2021-03-01"),by = "1 day"))) %>%
  tbl_df() %>%
  dplyr::mutate(Date=seq.Date(ymd("2020-10-14"),ymd("2021-03-01"),by = "1 day"))

break_even_date.increase.swiss <- 
  predicted.incidence.increase.swiss %>% filter(value>60) %>% slice(nrow(.)) %>% .[["Date"]]


# DECREASE in NOVEMBER
df.fit.decrease.swiss <- 
  df.switzerland.positive %>%
  filter(Date>=ymd("2020-11-09"))

fit.incidence.decrease.swiss <- 
  lm(log10(INCIDENCE)~Date,data=df.fit.decrease.swiss)

summary(fit.incidence.decrease.swiss)

predicted.incidence.decrease.swiss <- 
  10^predict(fit.incidence.decrease.swiss,
             data.frame(Date=seq.Date(ymd("2020-11-09"),ymd("2021-06-01"),by = "1 day"))) %>%
  tbl_df() %>%
  dplyr::mutate(Date=seq.Date(ymd("2020-11-09"),ymd("2021-06-01"),by = "1 day"))

break_even_date.decrease.swiss <- 
  predicted.incidence.decrease.swiss %>% filter(value>60) %>% slice(nrow(.)) %>% .[["Date"]]


### POSITIVE PERCENTAGE

df.switzerland.positive.perc_positive <- df.switzerland %>% 
  group_by(Datum) %>% 
  dplyr::mutate(Num_Test=sum(Number_of_tests)) %>% 
  filter(Outcome_tests=="Positive") %>% 
  dplyr::mutate(Perc_Positive=sum(Number_of_tests)/Num_Test) %>%
  rename(Date=Datum,
         NewPositive=Number_of_tests)

## Percent positive
ggplot(df.switzerland.positive.perc_positive,aes(x=Date,y=Perc_Positive)) +
  geom_line() +
  scale_x_date(date_breaks = "2 weeks",
               limits=c(dmy("26-02-2020"),dmy("01-01-2021")),
               date_labels = "%d-%m") +
  geom_vline(xintercept = unique(floor_date(seq.Date(dmy("01-08-2020"),
                                                     dmy("01-08-2030"),by="1 day"),"month"))) +
  theme(axis.text.x = element_text(angle = 90)) +
  labs(x="Date",y="% Positive") + 
  scale_y_continuous(labels = scales::percent)
  
## Incidence
df.switzerland.positive %>%
  ggplot(.,aes(x=Date,y=INCIDENCE)) +
  geom_point() +
  scale_x_date(date_breaks = "2 weeks",limits=c(dmy("26-02-2020"),dmy("01-05-2021")),date_labels = "%d-%m") +
  scale_y_continuous(limits=c(0,1750),breaks=seq(0,1750,by=250)) +
  geom_hline(yintercept = 60) +
  geom_abline(slope = -1,intercept = 200) +
  geom_line(data=predicted.incidence.increase.swiss,aes(x=Date,y=value),color="red") +
  geom_line(data=predicted.incidence.decrease.swiss,aes(x=Date,y=value),color="green") +
  geom_vline(xintercept = unique(floor_date(seq.Date(dmy("01-08-2020"),dmy("01-08-2030"),by="1 day"),"month"))) +
  theme_bw(base_size = 12) +
  # geom_vline(xintercept = break_even_date,color="red") +
  theme(axis.text.x = element_text(angle = 90)) +
  labs(x="Date",y="14-day Incidence Per 100,000")

```

## "CH+60" RULE

```{r}

df.ch60 <- bind_rows(df %>% dplyr::mutate(Country="DK"),
           df.switzerland.positive %>% dplyr::mutate(Country="CH")) %>% 
  dplyr::select(Date,INCIDENCE,Country) %>% 
  spread(Country,INCIDENCE) %>% 
  dplyr::mutate(Diff60=DK-(CH+60),
                Zero=0) %>% 
  filter(Date>=dmy("01-03-2020"))


  ggplot(df.ch60,aes(x=Date,y=Diff60)) +
  geom_line() +
  geom_ribbon(data=df.ch60,aes(ymin=Diff60, ymax=Zero), fill="green") +
  scale_y_continuous(breaks=seq(-1000,50,by=100),limits=c(-1000,50)) +
  geom_hline(yintercept = 0,color="gray50") +
  theme_bw(base_size = 10) +
  theme(axis.text.x = element_text(angle = 90)) +
  scale_x_date(date_breaks = "2 weeks",limits=c(dmy("26-02-2020"),dmy("01-02-2021")),date_labels = "%d-%m") +
  geom_vline(xintercept = unique(floor_date(seq.Date(dmy("01-03-2020"),dmy("01-08-2030"),by="1 day"),"month"))) +
    labs(x=NULL,y="Forskel i 14-dages incidence per 100.000 (DK - 'CH+60')")


```

## "CH+60" RULE

```{r}

df.ch60 <- bind_rows(df %>% dplyr::mutate(Country="DK"),
           df.switzerland.positive %>% dplyr::mutate(Country="CH")) %>% 
  dplyr::select(Date,INCIDENCE,Country) %>% 
  spread(Country,INCIDENCE) %>% 
  dplyr::mutate(Diff60=DK-(CH+60),
                Zero=0) %>% 
  filter(Date>=dmy("01-03-2020"))


  ggplot(df.ch60,aes(x=Date,y=Diff60)) +
  geom_line() +
  geom_ribbon(data=df.ch60,aes(ymin=Diff60, ymax=Zero), fill="green") +
  scale_y_continuous(breaks=seq(-1000,50,by=100),limits=c(-1000,50)) +
  geom_hline(yintercept = 0,color="gray50") +
  theme_bw(base_size = 10) +
  theme(axis.text.x = element_text(angle = 90)) +
  scale_x_date(date_breaks = "2 weeks",limits=c(dmy("01-11-2020"),dmy("01-01-2021")),date_labels = "%d-%m") +
  geom_vline(xintercept = unique(floor_date(seq.Date(dmy("01-03-2020"),dmy("01-08-2030"),by="1 day"),"month"))) +
    labs(x=NULL,y="Forskel i 14-dages incidence per 100.000 (DK - 'CH+60')")


```



















