on:
  push:
     branches:
       - main
  schedule:
    - cron:  '10 12 * * *' # runs every day numbers are out at 14:00

name: dk-covid-render

jobs:
  bookdown:
    name: renderbook
    #runs-on: macOS-latest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: r-lib/actions/setup-r@v1
      - uses: r-lib/actions/setup-pandoc@v1
      - name: Rvest dependencies 1
        run: sudo apt-get update
      - name: Rvest dependencies 2
        run: sudo apt-get -y install xml2 openssl libxml2
      - name: Rvest dependencies 3
        run: sudo apt-get update
      - name: Rvest dependencies 4
        run: sudo apt-get -y install libxml2-dev libmariadb-dev
      - name: Rvest dependencies 5
        run: sudo apt-get update
      - name: Rvest dependencies 6
        run: sudo apt-get -y install libcurl4-gnutls-dev
      - name: Install rvest
        run: Rscript -e 'install.packages(c("rvest"))'
      - name: Enable Rjava
        run: sudo R CMD javareconf
      - name: Install Rjava before tabulizer
        run:  Rscript -e 'install.packages("rJava"); library(rJava); install.packages("devtools");devtools::install_github("ropensci/tabulizer", args="--no-multiarch")'
      - name: Install rmarkdown
        run: Rscript -e 'install.packages(c("rmarkdown","bookdown","pacman","devtools","RCurl","rPref","rvest","epibasix","tabulizer"))'
      - name: Render Book
        run: Rscript -e 'bookdown::render_book("index.Rmd")'
      - uses: actions/upload-artifact@v1
        with:
          name: _book
          path: _book/

  checkout-and-deploy:
    runs-on: ubuntu-latest
    needs: bookdown
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Download artifact
      uses: actions/download-artifact@v2
      with:
        name: _book # optional
        path: _book # optional
    - name: Deploy to GitHub Pages
      uses: Cecilapp/GitHub-Pages-deploy@v3
      with:
        build_dir: _book/
        email: ${{ secrets.EMAIL }}optional
        jekyll: no                     # optional
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        EMAIL: ${{ secrets.EMAIL }} 
        BUILD_DIR: _book/
